# Generated by Django 6.0.1 on 2026-02-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('gandhinagar', 'Gandhinagar'), ('ahmedabad', 'Ahmedabad'), ('Mahesana', 'Mahesana')])),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Review', models.TextField()),
            ],
            options={
                'db_table': 'college',
            },
        ),
    ]
