# Generated by Django 6.0.1 on 2026-02-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('groceries', 'Groceries'), ('books', 'Books')])),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'shop_product',
            },
        ),
    ]
