# Generated by Django 6.0.1 on 2026-02-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0006_rename_inspection_report_inspectionreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='schedule_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer')], default='buyer', max_length=50),
        ),
    ]
