# Generated by Django 6.0.1 on 2026-02-10 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0007_alter_inspectionreport_score_alter_offer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Test.listing'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(default='0', max_length=17, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=50),
        ),
    ]
