# Generated by Django 6.0.1 on 2026-02-10 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0009_alter_transaction_buyer_alter_transaction_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
