# Generated by Django 6.0.1 on 2026-02-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0010_alter_inspectionreport_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
