# Generated by Django 6.0.1 on 2026-02-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='serviceDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
