# Generated by Django 6.0.1 on 2026-02-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serivce',
            name='review',
            field=models.CharField(max_length=100),
        ),
    ]
