# Generated by Django 6.0.1 on 2026-02-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_serivce_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serivce',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='serivce',
            name='review',
            field=models.TextField(),
        ),
    ]
